dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Controllers/ClienteController.cs
using MSDPortal.Application;
using MSDPortal.Application.Entidades;
using MSDPortal.Domain.Interfaces.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MSDPortal.Presentation.Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ClienteService _clienteService;

        public ClienteController(ClienteService clienteService)
        {
            _clienteService = clienteService;
        }

        // GET: Cliente
        public async Task<ActionResult> Index()
        {
            List<Cliente> listaClientes = await _clienteService.GetAll();
            return View(listaClientes);
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        public async Task<ActionResult> Create(Cliente model)
        {
            try
            {
                await _clienteService.Add(model);
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public async Task<ActionResult> Edit(int id)
        {

            Cliente cliente = await _clienteService.Get(id);
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Cliente model)
        {
            try
            {
                await _clienteService.Update(model);

                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int id)
        {

            return View(new Cliente());
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Cliente model)
        {
            try
            {
                // TODO: Add delete logic here
                _clienteService.Delete(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Controllers/ProdutoController.cs
using MSDPortal.Application;
using MSDPortal.Application.Entidades;
using MSDPortal.Domain.Interfaces.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MSDPortal.Presentation.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ProdutoService _produtoService;
        
        public ProdutoController(ProdutoService produtoService)
        {
            _produtoService = produtoService;
        }
        
        // GET: Produto
        public async Task<ActionResult> Index()
        {
          List<Produto> listaProdutos = await _produtoService.GetAll();
          return View(listaProdutos);
        }

        // GET: Produto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public async Task<ActionResult> Create(Produto model)
        {
            try
            {
               await _produtoService.Add(model);
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public async Task<ActionResult> Edit(int id)
        {

            Produto produto = await _produtoService.Get(id);
            return View(produto);
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Produto model)
        {
            try
            {
                await _produtoService.Update(model);

                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {

            return View(new Produto());
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Produto model)
        {
            try
            {
                // TODO: Add delete logic here
                _produtoService.Delete(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_Footer.cshtml
 


    <footer class="main-footer">
        <div class="social-media-footer" style="margin-top:10px">

            <a href="#"><i class="fab fa-instagram" style="color:#000; padding:10px"></i></a>
            <a href="#"><i class="fab fa-twitter" style="color:#000;padding:10px;"></i></a>
            <a href="#"><i class="fab fa-facebook-f" style="color:#000;padding:10px;"></i></a>

        </div>
        <div class="float-right d-none d-sm-block logo-footer" style="margin-bottom:5px">
           @* <img width="132" height="65" style="margin:auto" src="https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png" class="custom-logo" alt="MSD Salud Animal Brazil" srcset="https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png 532w, https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/08/msd-saude-animal-logo.png?resize=300,149 300w" sizes="(max-width: 532px) 100vw, 532px">*@
        </div>

    </footer>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <title>Projeto Estudo</title>
    @Html.Partial("AdminLTE/_Styles")
    <link rel="stylesheet" href="~/Content/site.css" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="//cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
</head>

<body class="hold-transition sidebar">

    <div class="wrapper">
        @Html.Partial("AdminLTE/_TopNavigation")
        @Html.Partial("AdminLTE/_MainNavigation")
        
            <div class="content-wrapper">
                <div class="content-header">
                    <div class="container-fluid ">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1 class="m-0 text-dark"></h1>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="container-fluid pb-5">
                        @RenderBody()
                    </div>
                </div>
            </div>
        
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>

            </div>
        </aside>
        @Html.Partial("AdminLTE/_Footer")
    </div>
    @Html.Partial("AdminLTE/_Scripts")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_LayoutAddBackground.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
  
    <title>MSD Portal</title>
    @Html.Partial("AdminLTE/_Styles")
    <link rel="stylesheet" href="~/Content/site.css" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="//cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
    @*<script src="~/adminlte/js/adminlte.js"></script>*@

    <style>
        .content-wrapper {
            margin-left: 0 !important;
        }

        :not(.layout-fixed) .main-sidebar {
            height: inherit;
            min-height: 100%;
            position: absolute;
            top: 0;
            left: 0 !important;
        }

        .content {
            margin-left: 250px !important;
        }
    </style>
    <script>
        $(document).ready(function () {

            $('#svgButtonArrow').click(function () {
                debugger;

                //if (!$('body').hasClass('colapseArrow'))
                if ($('#svgButtonArrow').hasClass('colapseArrow')) {

                    $('#svgButtonArrow').addClass('showArrow');
                    $('#svgButtonArrow').removeClass('colapseArrow');
                    $('[data-widget="pushmenu"]').PushMenu("expand");
                    $('.user-panel').css('border-bottom', '1px solid #4f5962');
                    return false;
                }
                else {
                    $('.user-panel').css('border-bottom', 'none');

                    $('#svgButtonArrow').addClass('colapseArrow');
                    $('#svgButtonArrow').removeClass('showArrow');
                    $('[data-widget="pushmenu"]').PushMenu("collapse");
                    return false;
                }



            })
        });

    </script>
</head>

<body class="hold-transition sidebar">

    <div class="wrapper">
        @Html.Partial("AdminLTE/_TopNavigation")
        @*@Html.Partial("AdminLTE/_MainNavigationSemNavigation")*@
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"></h1>
                        </div>

                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            @*<img src="~/Content/images/aba.svg" id="svgButtonArrow" data-auto-collapse-size="768" data-widget="pushmenu" />*@
        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>

            </div>
        </aside>
        @Html.Partial("AdminLTE/_Footer")
    </div>
    @Html.Partial("AdminLTE/_Scripts")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_LayoutNotLogged.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>MSD Portal</title>
    @Html.Partial("AdminLTE/_Styles")
    <link rel="stylesheet" href="~/Content/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/adminlte/js/adminlte.js"></script>
    <script>
        $(document).ready(function () {

            $('#svgButtonArrow').click(function () {
                debugger;
                //if (!$('body').hasClass('colapseArrow'))
                $('#svgButtonArrow').toggleClass('colapseArrow', 9000);


            })
        });

    </script>
</head>
@{
    if (Context.User.Identity.IsAuthenticated)
    {
        Layout = "_Layout";
    }
    else
    {
        Layout = "../_NotLogged/_NotLoggedLayout";
    }
}
<body class="hold-transition sidebar">
    <div class="wrapper">
        @Html.Partial("AdminLTE/_TopNavigation")
        @Html.Partial("AdminLTE/_MainNavigation")
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"></h1>
                        </div>

                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            @*<img src="~/Content/images/aba.svg" id="svgButtonArrow" data-auto-collapse-size="768" data-widget="pushmenu" />*@
        </div>
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <a class="nav-link" data-widget="control-sidebar" href="#">Toggle Control Sidebar</a>

            </div>
        </aside>
        @Html.Partial("AdminLTE/_Footer")
    </div>
    @Html.Partial("AdminLTE/_Scripts")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/adminlte/js")
    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_MainNavigation.cshtml
    <aside class="main-sidebar  sidebarColor elevation-4">

        <div class="mt-2 pt-1 mb-0 d-flex" style="">


           
                 
        </div>
        <div class="user-panel mt-2 pb-1 mb-1   d-flex">

        </div>
        <div class="sidebar sidebarT">



            <nav class="mt-2">

                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                    <li class="nav-item ">

                        <a href="@Url.Action("Index", "Home")" class="nav-link">

                            Home

                        </a>

                    </li>
                    <li class="nav-item">

                        <a href="@Url.Action("Index", "Produto")" class="nav-link ">

                            Produto

                        </a>

                    </li>
                    </li>
                    <li class="nav-item">

                        <a href="@Url.Action("Index", "Cliente")" class="nav-link ">

                            Cliente

                        </a>

                    </li>
                </ul>
            </nav>
        </div>
    </aside>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_MainNavigationSemNavigation.cshtml
@using Microsoft.AspNet.Identity



<aside class="main-sidebar  sidebarColor elevation-4">

    <div class="mt-2 pt-1 mb-0 d-flex" style="">


        <img width="110" height="38" style="margin:auto" src="~/Content/images/LOGO2.png"
             class="custom-logo" alt="MSD Salud Animal Brazil" sizes="(max-width: 532px) 100vw, 532px">
    </div>
    <div class="user-panel mt-2 pb-1 mb-1   d-flex">

    </div>
    <div class="sidebar sidebarT">



      
    </div>
</aside>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_Scripts.cshtml
<script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
<script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/adminlte/js/adminlte.min.js"></script>


<script>
    $(document).ready(function () {
        $("#telefone").inputmask("mask", { "mask": "(99) 9999-99999" });
        $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
        $("#cnpj").inputmask("mask", { "mask": "99.999.999/9999-99" }, { reverse: true });
        $("#cep").inputmask("mask", { "mask": "99999-999" });
        $("#nascimento").inputmask("mask", { "mask": "99/99/9999" });
        $("#preco").inputmask("mask", { "mask": "999.999,99" }, { reverse: true });
        $("#valor").inputmask("mask", { "mask": "#.##9,99" }, { reverse: true });
        $("#ip").inputmask("mask", { "mask": "999.999.999.999" });
    });
</script>

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_Styles.cshtml
<link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="~/adminlte/css/adminlte.min.css">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

dotnet-portalclientemsdcombr/MSDPortal.Presentation.Web/Views/Shared/AdminLTE/_TopNavigation.cshtml
 <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white   pb-3" style="height:66px; ">
    <!-- Left navbar links -->
    <ul class="navbar-nav" style="margin:auto;">
        <li class="nav-item">
            @* <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>*@
        </li>



        <li class="nav-item d-none d-sm-inline-block" style="padding-right:45px; letter-spacing:1px;">
            <a id="linkHome" href="@Url.Action("Index", "Produto", new {  })" class="menuTop-link nav-link text-uppercase font-weight-bold ">Produtos</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block" style="padding-right:45px; letter-spacing:1px;">
            <a id="linkHome" href="@Url.Action("Index", "Cliente", new {  })" class="menuTop-link nav-link text-uppercase font-weight-bold ">Cliente</a>
        </li>

    </ul>


        <!-- Right navbar links -->
        <div class="navbar-nav mr-auto">
            <div class="saudacao" style="width:100%; font-size: 9pt;">
    @*<div class="primeiraLinha" style="">
        <span style="color:#999; font-weight:bold"> OLÁ,</span>
        <span style="color:#0dbab1; font-weight:bold;"> ALESSANDRO MELO JR.</span>
    </div>
    <span style="color:#999;">LOJA,</span>
    <span style="color:#999; font-weight:bold;">xxx</span>*@
                @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
    </div>
    </div>
</nav>
<!-- /.navbar -->




 <script>
     window.onload = function () {
    if(document.location.pathname === "/"){
        document.querySelector("#linkHome").classList.add("menuTop-link-active");
      }
          
}
   

 </script>


 